#!/usr/bin/env python3
from pathlib import Path


def replace_once(path, old, new):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if new in s:
        print('already patched', path); return
    if s.count(old)!=1:
        raise SystemExit(f'{path}: expected one marker, got {s.count(old)}')
    p.write_text(s.replace(old,new),encoding='utf-8')
    print('patched',path)

replace_once('CMakeLists.txt',
'''cad_add_test(trade_episode_validation_tests tests/trade_episode_validation_test.cpp trade_episode_validation)
set_tests_properties(trade_episode_validation PROPERTIES WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
cad_add_test(robustness_sampler_tests tests/robustness_test.cpp robustness_sampler)
''',
'''cad_add_test(trade_episode_validation_tests tests/trade_episode_validation_test.cpp trade_episode_validation)
set_tests_properties(trade_episode_validation PROPERTIES WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
cad_add_test(final_realism_tests tests/final_realism_test.cpp final_realism)
cad_add_test(robustness_sampler_tests tests/robustness_test.cpp robustness_sampler)
''')

readme=Path('README.md'); s=readme.read_text(encoding='utf-8')
marker='- **Risk block:** recession frequency plus 90th-percentile inflation and federal-debt stress outcomes.\n'
insert='''- **Dynamic implementation paths:** optimizer controls remain finite amplitudes, but fiscal stimulus, productive investment, negotiated relief, targeted relief and diversification follow explicit 12-quarter ramp/persistence/fade rules. The realized paths are returned in every scenario for auditability.\n- **Tail and stress-regime risk:** large standardized innovations receive an explicit heavy-tail multiplier and financial/recession/high-tariff starting states amplify macro shocks. These are registered sensitivity assumptions, not estimated tail probabilities or regime-transition parameters.\n'''
if insert not in s:
    if marker not in s: raise SystemExit('README risk marker missing')
    s=s.replace(marker,insert+marker)
marker2='- `POST /api/v2/welfare` — the full 3×3 delegation-preference/risk grid, rerunning the production policy and sector optimization for every profile.\n'
new2='- `POST /api/v2/welfare` — the full 3×3 delegation-preference/risk grid plus six named ±20% internal-component weight profiles (BoC inflation, federal debt, U.S. inflation), rerunning production optimization for every profile while keeping the institutional mandate fixed.\n'
if marker2 in s: s=s.replace(marker2,new2)
if 'tools/build_oecd_bilateral_io.py' not in s:
    trade_marker='The repository also carries `data/backtests/2018-section232-trade-validation.csv`'
    oecd='''`tools/build_oecd_bilateral_io.py` accepts an OECD ICIO ZIP obtained directly from the official OECD distribution plus a reviewed fractional industry crosswalk. It generates Canada←U.S. and U.S.←Canada intermediate-input sourcing-share matrices with SHA-pinned provenance. Automated production activation remains disabled until official source bytes and the reviewed crosswalk are available; third-party mirrors are not accepted as empirical source material.\n\n'''
    if trade_marker not in s: raise SystemExit('README trade validation marker missing')
    s=s.replace(trade_marker,oecd+trade_marker)
readme.write_text(s,encoding='utf-8')

doc=Path('docs/MODEL_ROBUSTNESS_V2.md'); s=doc.read_text(encoding='utf-8')
old='''The internal BoC/federal/U.S. component-loss coefficients remain fixed in this milestone. `mandateWeightsFixed=true` is audited across every preference profile. Sensitivity of those internal component weights is a later extension and should use a typed weight registry rather than anonymous literals.\n'''
new='''The institutional mandate remains fixed, but the former anonymous internal BoC/federal/U.S. loss-function literals are now typed as `DecisionLossWeights`. The default V2 grid adds six named one-dimensional ±20% internal-weight profiles for the BoC inflation penalty, federal debt penalty and U.S. inflation penalty. Results separately report `mandateWeightsFixed` and `internalComponentWeightsFixed`, so normative/model-design sensitivity cannot be mistaken for changing the mandate.\n'''
if old in s: s=s.replace(old,new)
old2='''22. Replace the explicitly provisional U.S. production-network proxy with the versioned BEA 20-sector artifact generated by `tools/build_bea_io_matrix.py` once authenticated source extraction is available.\n23. Add typed sensitivity for internal component-loss weights, explicitly separating mandate-fixed from assumed welfare coefficients.\n24. Expand historical validation beyond the three macro-policy fixtures. The 2018 Section 232 steel/aluminum fixture now provides a separate treated-product trade-channel stress/falsification benchmark without pretending to be a complete 18-state macro vintage.\n25. Improve archival real-time vintage quality for reconstructed market-state inputs where open historical feeds become available.\n'''
new2='''22. Replace the explicitly provisional U.S. production-network proxy with the versioned BEA 20-sector artifact generated by `tools/build_bea_io_matrix.py` once authenticated source extraction is available.\n23. Activate Canada↔U.S. bilateral intermediate sourcing from the official OECD ICIO archive once official bytes and a reviewed fractional industry crosswalk are supplied; `tools/build_oecd_bilateral_io.py` now provides the fail-closed aggregation/provenance path.\n24. Expand historical validation beyond the three macro-policy fixtures. The 2018 Section 232 steel/aluminum fixture provides a separate treated-product trade-channel stress/falsification benchmark without pretending to be a complete 18-state macro vintage.\n25. Improve archival real-time vintage quality for reconstructed market-state inputs where open historical feeds become available.\n'''
if old2 in s: s=s.replace(old2,new2)
doc.write_text(s,encoding='utf-8')

registry=Path('data/calibration/source_registry.csv'); s=registry.read_text(encoding='utf-8')
if 'oecd_icio_2025' not in s:
    s=s.rstrip()+'''\noecd_icio_2025,OECD,"Inter-Country Input-Output Tables 2025 edition (2016-2022 block)",official_icio,annual,official_archive,https://www.oecd.org/en/data/insights/data-explainers/2024/05/inter-country-input-output-tables.html,"Official source for future Canada-US bilateral intermediate-input sourcing shares. Production activation requires an official OECD archive and reviewed ICIO-industry crosswalk; automated CDN access is not assumed."\n'''
    registry.write_text(s,encoding='utf-8')
    print('appended OECD ICIO source registry entry')
