const groups={"Monetary & prices":[['policyRate','Policy rate',2.75,'%'],['inflation','CPI inflation',2.4,'%'],['coreInflation','Core inflation',2.6,'%'],['expectations','Expectations',2.2,'%']],"Real economy":[['gdpGrowth','GDP growth',1.6,'%'],['outputGap','Output gap',-.4,'%'],['unemployment','Unemployment',6.4,'%'],['wageGrowth','Wage growth',3.5,'%'],['productivity','Productivity',.8,'%']],"Financial & external":[['creditSpread','Credit spread',1.35,'%'],['housingGap','Housing valuation gap',7,'%'],['householdDebt','Household debt / income',178,'%'],['usdcad','USD / CAD',1.38,''],['oil','WTI oil',74,'$']],"Federal position":[['fiscalBalance','Balance / GDP',-1.2,'%'],['federalDebt','Debt / GDP',42,'%'],['programGrowth','Program growth',2,'%'],['infrastructure','Capital impulse',.3,'%']]};
const root=document.querySelector('#inputs');Object.entries(groups).forEach(([name,fields])=>{let box=document.createElement('div');box.className='group';box.innerHTML=`<div class="group-title">${name}</div>`;fields.forEach(([id,label,value,unit])=>box.innerHTML+=`<div class="field"><label for="${id}">${label}</label><div><input id="${id}" type="number" step="0.1" value="${value}" data-default="${value}"><small>${unit}</small></div></div>`);root.append(box)});
let result,selected,series='inflationPath';
const fmt=(x,d=1)=>Number(x).toFixed(d);const payload=()=>Object.fromEntries([...document.querySelectorAll('input')].map(x=>[x.id,+x.value]));
async function evaluate(){const btn=document.querySelector('#run');btn.firstChild.textContent='Running 3,500 paths… ';btn.disabled=true;try{let res=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});result=await res.json();selected=result.scenarios[0];render()}finally{btn.firstChild.textContent='Evaluate policy mix ';btn.disabled=false}}
function render(){document.querySelector('#confidence').textContent=fmt(result.confidence,0)+'%';document.querySelector('#signal').textContent=result.signal;document.querySelector('#rationale').textContent=result.rationale;document.querySelector('#regime').textContent=result.regime;document.querySelector('#neutral').textContent=fmt(result.neutralRate,2)+'%';document.querySelector('#gap').textContent=(result.policyGap>=0?'+':'')+fmt(result.policyGap,2)+' pp';
 document.querySelector('#cards').innerHTML=result.scenarios.map((s,i)=>`<article class="card ${i===0?'best':''} ${s.id===selected.id?'selected':''}" data-id="${s.id}"><div class="eyebrow">${i+1 < 10?'0':''}${i+1} · ${s.move>0?'+':''}${s.move} bp</div><h3>${s.name}</h3><p>${s.description}</p><div class="score">${fmt(s.score,0)}<small> / 100 joint</small></div><div class="split"><i style="width:${s.bocScore}%"></i><i style="width:${s.federalScore}%"></i></div><dl><div><dt>INFLATION</dt><dd>${fmt(s.inflation)}%</dd></div><div><dt>GROWTH</dt><dd>${fmt(s.growth)}%</dd></div><div><dt>UNEMPLOYMENT</dt><dd>${fmt(s.unemployment)}%</dd></div><div><dt>RECESSION RISK</dt><dd>${fmt(s.recessionRisk,0)}%</dd></div></dl></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{selected=result.scenarios.find(s=>s.id===c.dataset.id);render()});draw()}
function draw(){document.querySelector('#chartTitle').textContent=selected.name+' · 12-quarter projection';let a=selected[series],min=Math.min(...a),max=Math.max(...a);let pad=(max-min)*.2||1;min-=pad;max+=pad;const x=i=>55+i*72,y=v=>235-(v-min)/(max-min)*190;let path=a.map((v,i)=>(i?'L':'M')+x(i)+' '+y(v)).join(' '),area=path+` L ${x(11)} 235 L 55 235 Z`;let svg=`<defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#6f9f91" stop-opacity=".3"/><stop offset="1" stop-color="#6f9f91" stop-opacity="0"/></linearGradient></defs>`;for(let i=0;i<4;i++){let yy=45+i*63,v=max-i*(max-min)/3;svg+=`<line class="grid" x1="55" y1="${yy}" x2="850" y2="${yy}"/><text class="axis-label" x="5" y="${yy+3}">${fmt(v,1)}${series==='debtPath'?'%':''}</text>`}svg+=`<path class="area" d="${area}"/><path class="line" d="${path}"/>`;a.forEach((v,i)=>svg+=`<circle class="dot" cx="${x(i)}" cy="${y(v)}" r="3"/><text class="axis-label" x="${x(i)-7}" y="258">Q${i+1}</text>`);document.querySelector('#chart').innerHTML=svg}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.tabs .active').classList.remove('active');b.classList.add('active');series=b.dataset.series;draw()});document.querySelector('#run').onclick=evaluate;document.querySelector('#reset').onclick=()=>{document.querySelectorAll('input').forEach(x=>x.value=x.dataset.default);evaluate()};evaluate();
