let settings={},result,noTariff,selected,series='inflationPath';
const $=s=>document.querySelector(s),fmt=(x,d=1)=>Number(x).toFixed(d),signed=(x,suffix='%')=>(x>=0?'+':'')+fmt(x)+suffix;
const tariff=$('#usTariff');
function updateTariff(){ $('#tariffValue').textContent=tariff.value+'%';document.querySelectorAll('.presets button').forEach(b=>b.classList.toggle('active',b.dataset.rate===tariff.value)); }
async function loadBaseline(){try{const b=await fetch('/api/baseline').then(r=>r.json());settings=b.settings;$('#dataStatus').textContent=b.status==='live'?'Live official feeds':'Documented cached baseline';$('#asOf').textContent='As of '+new Date(b.asOf).toLocaleString();$('#sync').textContent=b.status==='live'?'Official feeds synchronized':'Baseline fallback active';$('#sourceList').innerHTML=b.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noreferrer"><b>${s.name}</b><span>${s.fields} ↗</span></a>`).join('');}catch(e){settings={};$('#dataStatus').textContent='Baseline unavailable';$('#sync').textContent='Connection error';}evaluate()}
async function evaluate(){const btn=$('#run');btn.disabled=true;btn.firstChild.textContent='Searching 144 policy mixes… ';const preferences={canadaPriority:+$('#canadaPriority').value,usPriority:+$('#usPriority').value,riskAversion:+$('#riskAversion').value,cooperationCeiling:+$('#cooperationCeiling').value};try{const request=rate=>fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settings,...preferences,usTariff:rate})}).then(r=>r.json());[result,noTariff]=await Promise.all([request(+tariff.value),request(0)]);selected=result.scenarios[0];render();}finally{btn.disabled=false;btn.firstChild.textContent='Run again now ';}}
function render(){const best=result.scenarios[0],zero=noTariff.scenarios.find(s=>s.id===best.id)||noTariff.scenarios[0];$('#confidence').textContent=fmt(result.confidence,0)+'%';$('#searchCount').textContent=`${result.candidatesExamined} generated mixes + 12 expert strategies evaluated`;$('#signal').textContent=result.signal;$('#rationale').textContent=result.rationale;$('#regime').textContent=result.regime;$('#neutral').textContent=fmt(result.neutralRate,2)+'%';$('#gap').textContent=signed(result.policyGap,' pp');$('#impactGrowth').textContent=signed(best.growth-zero.growth,' pp');$('#impactCost').textContent=fmt(best.costOfLiving)+'%';$('#impactExports').textContent=signed(best.exports);$('#impactRisk').textContent=fmt(best.recessionRisk,0)+'%';
 $('#cards').innerHTML=result.scenarios.map((s,i)=>`<article class="card ${i===0?'best':''} ${s.id===selected.id?'selected':''}" data-id="${s.id}"><div class="rank">${String(i+1).padStart(2,'0')}</div><div class="eyebrow">${s.id==='custom'?'AUTONOMOUS SEARCH · ':''}${s.move>0?'+':''}${s.move} bp · score ${fmt(s.score,0)}</div><h3>${s.name}</h3><p>${s.description}</p><div class="outcomes"><div><span>GDP</span><b>${fmt(s.growth)}%</b></div><div><span>Inflation</span><b>${fmt(s.inflation)}%</b></div><div><span>Jobs</span><b>${fmt(s.unemployment)}%</b></div><div><span>Debt</span><b>${fmt(s.debt)}%</b></div></div><div class="party-scores"><span>Canada mandate <b>${fmt(s.bocScore,0)}</b></span><span>Canada public <b>${fmt(s.federalScore,0)}</b></span><span>United States <b>${fmt(s.usScore,0)}</b></span></div><div class="risk"><span>Recession risk</span><i><em style="width:${s.recessionRisk}%"></em></i><b>${fmt(s.recessionRisk,0)}%</b></div></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{selected=result.scenarios.find(s=>s.id===c.dataset.id);render()});draw()}
function draw(){if(!selected)return;$('#chartTitle').textContent=selected.name+' · 12-quarter projection';const a=selected[series],lo=Math.min(...a),hi=Math.max(...a),pad=(hi-lo)*.2||1,min=lo-pad,max=hi+pad,x=i=>55+i*72,y=v=>235-(v-min)/(max-min)*190;let path=a.map((v,i)=>(i?'L':'M')+x(i)+' '+y(v)).join(' '),svg='<defs><linearGradient id="fade" x2="0" y2="1"><stop stop-color="#b52b3a" stop-opacity=".22"/><stop offset="1" stop-color="#b52b3a" stop-opacity="0"/></linearGradient></defs>';for(let i=0;i<4;i++){let yy=45+i*63,v=max-i*(max-min)/3;svg+=`<line class="grid" x1="55" y1="${yy}" x2="850" y2="${yy}"/><text class="axis-label" x="5" y="${yy+3}">${fmt(v)}</text>`}svg+=`<path class="area" d="${path} L ${x(11)} 235 L 55 235 Z"/><path class="line" d="${path}"/>`;a.forEach((v,i)=>svg+=`<circle class="dot" cx="${x(i)}" cy="${y(v)}" r="3"/><text class="axis-label" x="${x(i)-7}" y="258">Q${i+1}</text>`);$('#chart').innerHTML=svg}
let timer;function schedule(){clearTimeout(timer);timer=setTimeout(evaluate,350)}tariff.oninput=()=>{updateTariff();schedule()};['canadaPriority','usPriority','riskAversion','cooperationCeiling'].forEach(id=>{$('#'+id).oninput=()=>{$('#'+id+'Value').textContent=$('#'+id).value+(id==='cooperationCeiling'?'%':'');schedule()}});document.querySelectorAll('.presets button').forEach(b=>b.onclick=()=>{tariff.value=b.dataset.rate;updateTariff();evaluate()});$('#run').onclick=evaluate;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.tabs .active').classList.remove('active');b.classList.add('active');series=b.dataset.series;draw()});$('#sourcesButton').onclick=()=>$('#sources').showModal();$('.close').onclick=()=>$('#sources').close();updateTariff();loadBaseline();
